title: "Experiment Details"
author: "Utku Turk and Ellen Lau"
bibliography: refs.bib
date: today
format:
  pdf:
      toc: false
      shift-heading-level-by: 1
      fig-pos: "H"
      fig-cap-location: top
      # number-sections: true
      geometry:
        - top=1in
        - right=.8in
        - bottom=1in
        - left=.8in
      link-citations: true
      linkcolor: blue
      include-in-header: 
        text: |
          \usepackage{fancyhdr}
          \usepackage{titling}
          \pagestyle{fancy}
          \fancyhf{}
          \renewcommand\maketitle{
            \fancyhead[C]{
              \thetitle
              \ifx \theauthor\empty  \else \ – \theauthor \fi
              \ifx \thedate\empty  \else \ – \thedate \ \fi
            }
          }
          \fancyfoot[C]{\thepage}